version: '3'

services:

  client:
    image: tidalpaladin/hw3
    hostname: client
    depends_on:
      - metaserver
      - server
    tty: true
    stdin_open: true
    environment:
      - PORT=32000
      - MODE=client
      - META=metaserver

  server:
    image: tidalpaladin/hw3
    hostname: server
    depends_on:
      - metaserver
    environment:
      - PORT=32000
      - MODE=server
      - META=metaserver

  metaserver:
    image: tidalpaladin/hw3
    hostname: metaserver
    environment:
      - PORT=32000
      - MODE=meta
      - META=metaserver
